<?php

declare(strict_types=1);

namespace SistemAtc\Marketplaces\MercadoPago\DTO\Response\CardTokens;

use SistemAtc\Marketplaces\Common\Traits\AutoHydrate;
use SistemAtc\Marketplaces\Common\Traits\CastToArray;
use SistemAtc\Marketplaces\Contracts\DTOInterface;
use SistemAtc\Marketplaces\MercadoPago\DTO\Response\Payments\Cardholder;

/**
 * Represents a tokenized card in the MercadoPago API. A card token is a secure, temporary
 * representation of card data generated by MercadoPago.js on the client side. It is used to
 * create payments without transmitting sensitive card details through the integrator's server.
 * Returned by CardTokenClient operations.
 */
final class CardTokenResponseDTO implements DTOInterface
{
    use AutoHydrate;
    use CastToArray;

    public function __construct(
        /** Unique token identifier used to reference this card token in payment requests. */
        public readonly ?string $id = null,

        /** Last four digits of the card number (for display/verification purposes). */
        public readonly ?string $lastFourDigits = null,

        /** First six digits (BIN) of the card number, used to identify the issuer and card type. */
        public readonly ?string $firstSixDigits = null,

        /** Four-digit expiration year of the card. */
        public readonly ?int $expirationYear = null,

        /** Two-digit expiration month of the card (1-12). */
        public readonly ?int $expirationMonth = null,

        /** ISO 8601 timestamp when the token was created. */
        public readonly ?string $dateCreated = null,

        /** ISO 8601 timestamp of the last update to the token. */
        public readonly ?string $dateLastUpdated = null,

        /** Cardholder name and identification data. */
        public readonly ?Cardholder $cardholder = null,

        /** Saved card identifier if the token was generated from a stored card. */
        public readonly ?int $cardId = null,

        /** Current status of the token (e.g. "active"). */
        public readonly ?string $status = null,

        /** ISO 8601 timestamp when the token expires and can no longer be used. */
        public readonly ?string $dateDue = null,

        /** Whether the card number passed Luhn algorithm validation. */
        public readonly ?bool $luhnValidation = null,

        /** Whether this token was created in production (true) or sandbox (false). */
        public readonly ?bool $liveMode = null,

        /** Whether the token requires ESC (E2E Security Code) for processing. */
        public readonly ?bool $requireEsc = null,

        /** Total number of digits in the card number. */
        public readonly ?int $cardNumberLength = null,

        /** Number of digits in the card's security code (CVV/CVC). */
        public readonly ?int $securityCodeLength = null,
    ) {}
}
