<?php

declare(strict_types=1);

namespace SistemAtc\Marketplaces\MercadoPago\DTO\Response\Orders;

use SistemAtc\Marketplaces\Common\Traits\AutoHydrate;
use SistemAtc\Marketplaces\Common\Traits\CastToArray;
use SistemAtc\Marketplaces\Contracts\DTOInterface;

/**
 * Represents the payment method details for an order payment or attempt. Contains all
 * method-specific data such as card tokens, boleto barcodes, Pix QR codes, installment counts,
 * and 3DS security information.
 */
final class PaymentMethod implements DTOInterface
{
    use AutoHydrate;
    use CastToArray;

    public function __construct(
        /** Payment method identifier (e.g., "visa", "pix", "bolbradesco"). */
        public readonly ?string $id = null,

        /** Payment method type (e.g., "credit_card", "debit_card", "bank_transfer", "ticket"). */
        public readonly ?string $type = null,

        /** Saved card identifier when using a stored card-on-file. */
        public readonly ?string $cardId = null,

        /** Tokenized card data generated by the MercadoPago.js SDK. */
        public readonly ?string $token = null,

        /** Number of installments selected by the buyer. */
        public readonly ?int $installments = null,

        /** Text that appears on the buyer's card statement for this charge. */
        public readonly ?string $statementDescriptor = null,

        /** URL of the printable payment ticket (boleto/lottery). */
        public readonly ?string $ticketUrl = null,

        /** Barcode content string for boleto or lottery-type payments. */
        public readonly ?string $barcodeContent = null,

        /** Payment reference code displayed to the buyer for off-line payments. */
        public readonly ?string $reference = null,

        /** External reference identifier for the payment method. */
        public readonly ?string $referenceId = null,

        /** Verification code for bank transfer or wallet payments. */
        public readonly ?string $verificationCode = null,

        /** Financial institution code processing the payment (e.g., bank code for PSE). */
        public readonly ?string $financialInstitution = null,

        /** Pix QR code string for copy-and-paste payments. */
        public readonly ?string $qrCode = null,

        /** Base64-encoded Pix QR code image. */
        public readonly ?string $qrCodeBase64 = null,

        /** Digitable line for boleto payments (numeric barcode representation). */
        public readonly ?string $digitableLine = null,

        /** End-to-end transaction identifier for Pix payments. */
        public readonly ?string $e2eId = null,

        /** URL to redirect the buyer for external payment authorization (e.g., bank redirect). */
        public readonly ?string $redirectUrl = null,

        /** 3D Secure and other transaction security details. */
        public readonly ?TransactionSecurity $transactionSecurity = null,

        /** (campo presente na resposta real, ausente no SDK oficial) */
        public readonly ?string $issuerId = null,
    ) {}
}
